# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_root(object):
    def setupUi(self, window_root):
        window_root.setObjectName("window_root")
        window_root.resize(852, 825)
        window_root.setStyleSheet("")
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        self.label_select_title = QtWidgets.QLabel(self.tab_home)
        self.label_select_title.setGeometry(QtCore.QRect(10, 320, 141, 21))
        self.label_select_title.setStyleSheet("QLabel {\n"
                                              "    background-color: rgba(0, 255, 255, 30)\n"
                                              "}")
        self.label_select_title.setObjectName("label_select_title")
        self.verticalFrame = QtWidgets.QFrame(self.tab_home)
        self.verticalFrame.setGeometry(QtCore.QRect(10, 340, 831, 131))
        self.verticalFrame.setStyleSheet("QFrame {\n"
                                         "    background-color: rgba(0, 255, 255, 30);\n"
                                         "    margin: 0;\n"
                                         "    padding: 0;\n"
                                         "}")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame1 = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame1.setStyleSheet("QFrame {\n"
                                            "    background-color: none;\n"
                                            "}")
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_window_title = QtWidgets.QLabel(self.horizontalFrame1)
        self.label_window_title.setMinimumSize(QtCore.QSize(80, 0))
        self.label_window_title.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_window_title.setStyleSheet("QLabel {\n"
                                              "    background-color: none;\n"
                                              "}")
        self.label_window_title.setObjectName("label_window_title")
        self.horizontalLayout.addWidget(self.label_window_title)
        self.text_window_title = QtWidgets.QLineEdit(self.horizontalFrame1)
        self.text_window_title.setObjectName("text_window_title")
        self.horizontalLayout.addWidget(self.text_window_title)
        self.verticalLayout.addWidget(self.horizontalFrame1)
        self.horizontalFrame2 = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame2.setStyleSheet("QFrame {\n"
                                            "    background-color: none;\n"
                                            "    border: 0px none;\n"
                                            "}")
        self.horizontalFrame2.setObjectName("horizontalFrame2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_size = QtWidgets.QLabel(self.horizontalFrame2)
        self.label_size.setMinimumSize(QtCore.QSize(80, 0))
        self.label_size.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_size.setObjectName("label_size")
        self.horizontalLayout_2.addWidget(self.label_size)
        self.text_size = QtWidgets.QLineEdit(self.horizontalFrame2)
        self.text_size.setObjectName("text_size")
        self.horizontalLayout_2.addWidget(self.text_size)
        self.label_xy = QtWidgets.QLabel(self.horizontalFrame2)
        self.label_xy.setObjectName("label_xy")
        self.horizontalLayout_2.addWidget(self.label_xy)
        self.text_xy = QtWidgets.QLineEdit(self.horizontalFrame2)
        self.text_xy.setObjectName("text_xy")
        self.horizontalLayout_2.addWidget(self.text_xy)
        self.label_pid = QtWidgets.QLabel(self.horizontalFrame2)
        self.label_pid.setStyleSheet("QLabel {\n"
                                     "    background-color: none;\n"
                                     "}")
        self.label_pid.setObjectName("label_pid")
        self.horizontalLayout_2.addWidget(self.label_pid)
        self.text_pid = QtWidgets.QLineEdit(self.horizontalFrame2)
        self.text_pid.setObjectName("text_pid")
        self.horizontalLayout_2.addWidget(self.text_pid)
        self.label_tid = QtWidgets.QLabel(self.horizontalFrame2)
        self.label_tid.setStyleSheet("QLabel {\n"
                                     "    background-color: none;\n"
                                     "}")
        self.label_tid.setObjectName("label_tid")
        self.horizontalLayout_2.addWidget(self.label_tid)
        self.text_tid = QtWidgets.QLineEdit(self.horizontalFrame2)
        self.text_tid.setObjectName("text_tid")
        self.horizontalLayout_2.addWidget(self.text_tid)
        self.verticalLayout.addWidget(self.horizontalFrame2)
        self.horizontalFrame3 = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame3.setStyleSheet("QFrame {\n"
                                            "    background-color: none;\n"
                                            "}")
        self.horizontalFrame3.setObjectName("horizontalFrame3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_process_path = QtWidgets.QLabel(self.horizontalFrame3)
        self.label_process_path.setMinimumSize(QtCore.QSize(80, 0))
        self.label_process_path.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_process_path.setObjectName("label_process_path")
        self.horizontalLayout_4.addWidget(self.label_process_path)
        self.text_process_path = QtWidgets.QLineEdit(self.horizontalFrame3)
        self.text_process_path.setObjectName("text_process_path")
        self.horizontalLayout_4.addWidget(self.text_process_path)
        self.verticalLayout.addWidget(self.horizontalFrame3)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame.setStyleSheet("QFrame {\n"
                                           "    background-color: none;\n"
                                           "}")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_status = QtWidgets.QLabel(self.horizontalFrame)
        self.label_status.setMinimumSize(QtCore.QSize(80, 0))
        self.label_status.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_23.addWidget(self.label_status)
        self.text_status = QtWidgets.QLineEdit(self.horizontalFrame)
        self.text_status.setObjectName("text_status")
        self.horizontalLayout_23.addWidget(self.text_status)
        self.label_status2 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_status2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_status2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_status2.setObjectName("label_status2")
        self.horizontalLayout_23.addWidget(self.label_status2)
        self.text_status2 = QtWidgets.QLineEdit(self.horizontalFrame)
        self.text_status2.setObjectName("text_status2")
        self.horizontalLayout_23.addWidget(self.text_status2)
        self.label_opacity_2 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_opacity_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_opacity_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_opacity_2.setObjectName("label_opacity_2")
        self.horizontalLayout_23.addWidget(self.label_opacity_2)
        self.text_opacity = QtWidgets.QLineEdit(self.horizontalFrame)
        self.text_opacity.setObjectName("text_opacity")
        self.horizontalLayout_23.addWidget(self.text_opacity)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.label_window_dock = QtWidgets.QLabel(self.tab_home)
        self.label_window_dock.setGeometry(QtCore.QRect(10, 480, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_window_dock.setFont(font)
        self.label_window_dock.setStyleSheet("QLabel {\n"
                                             "    background-color: rgba(74, 255, 155, 80);\n"
                                             "}")
        self.label_window_dock.setObjectName("label_window_dock")
        self.container_dock = QtWidgets.QFrame(self.tab_home)
        self.container_dock.setGeometry(QtCore.QRect(10, 500, 81, 121))
        self.container_dock.setStyleSheet("QFrame {\n"
                                          "    background-color: rgba(74, 255, 155, 80);\n"
                                          "}")
        self.container_dock.setObjectName("container_dock")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.container_dock)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_dock_left = QtWidgets.QPushButton(self.container_dock)
        self.button_dock_left.setObjectName("button_dock_left")
        self.gridLayout_2.addWidget(self.button_dock_left, 0, 0, 1, 1)
        self.button_dock_down = QtWidgets.QPushButton(self.container_dock)
        self.button_dock_down.setObjectName("button_dock_down")
        self.gridLayout_2.addWidget(self.button_dock_down, 1, 1, 1, 1)
        self.button_dock_up = QtWidgets.QPushButton(self.container_dock)
        self.button_dock_up.setObjectName("button_dock_up")
        self.gridLayout_2.addWidget(self.button_dock_up, 1, 0, 1, 1)
        self.button_dock_right = QtWidgets.QPushButton(self.container_dock)
        self.button_dock_right.setObjectName("button_dock_right")
        self.gridLayout_2.addWidget(self.button_dock_right, 0, 1, 1, 1)
        self.button_dock_h_center = QtWidgets.QPushButton(self.container_dock)
        self.button_dock_h_center.setMaximumSize(QtCore.QSize(90, 16777215))
        self.button_dock_h_center.setObjectName("button_dock_h_center")
        self.gridLayout_2.addWidget(self.button_dock_h_center, 2, 0, 1, 1)
        self.button_dock_v_center = QtWidgets.QPushButton(self.container_dock)
        self.button_dock_v_center.setMaximumSize(QtCore.QSize(90, 16777215))
        self.button_dock_v_center.setObjectName("button_dock_v_center")
        self.gridLayout_2.addWidget(self.button_dock_v_center, 2, 1, 1, 1)
        self.label_window_xy_title = QtWidgets.QLabel(self.tab_home)
        self.label_window_xy_title.setGeometry(QtCore.QRect(240, 480, 72, 21))
        self.label_window_xy_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_window_xy_title.setStyleSheet("QLabel {\n"
                                                 "    background-color: rgba(193, 255, 101, 100);\n"
                                                 "}")
        self.label_window_xy_title.setObjectName("label_window_xy_title")
        self.location = QtWidgets.QFrame(self.tab_home)
        self.location.setGeometry(QtCore.QRect(240, 500, 231, 91))
        self.location.setStyleSheet("QFrame {\n"
                                    "    background-color: rgba(193, 255, 101, 100);\n"
                                    "}")
        self.location.setObjectName("location")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.location)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalFrame_7 = QtWidgets.QFrame(self.location)
        self.horizontalFrame_7.setStyleSheet("QFrame {\n"
                                             "    border: 1px solid black;\n"
                                             "}")
        self.horizontalFrame_7.setObjectName("horizontalFrame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_left = QtWidgets.QLabel(self.horizontalFrame_7)
        self.label_left.setMinimumSize(QtCore.QSize(0, 0))
        self.label_left.setStyleSheet("QLabel {\n"
                                      "    border: none;\n"
                                      "    border-right: 1px solid black;\n"
                                      "    background-color: none;\n"
                                      "}")
        self.label_left.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_left.setObjectName("label_left")
        self.horizontalLayout_7.addWidget(self.label_left)
        self.input_left = QtWidgets.QLineEdit(self.horizontalFrame_7)
        self.input_left.setStyleSheet("QLineEdit {\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "")
        self.input_left.setObjectName("input_left")
        self.horizontalLayout_7.addWidget(self.input_left)
        self.gridLayout_3.addWidget(self.horizontalFrame_7, 0, 0, 1, 1)
        self.horizontalFrame_8 = QtWidgets.QFrame(self.location)
        self.horizontalFrame_8.setStyleSheet("QFrame {\n"
                                             "    border: 1px solid black;\n"
                                             "}")
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_right = QtWidgets.QLabel(self.horizontalFrame_8)
        self.label_right.setMinimumSize(QtCore.QSize(0, 0))
        self.label_right.setStyleSheet("QLabel {\n"
                                       "    border: none;\n"
                                       "    border-right: 1px solid black;\n"
                                       "}")
        self.label_right.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_right.setObjectName("label_right")
        self.horizontalLayout_8.addWidget(self.label_right)
        self.input_right = QtWidgets.QLineEdit(self.horizontalFrame_8)
        self.input_right.setStyleSheet("QLineEdit {\n"
                                       "    border: none;\n"
                                       "}\n"
                                       "")
        self.input_right.setObjectName("input_right")
        self.horizontalLayout_8.addWidget(self.input_right)
        self.gridLayout_3.addWidget(self.horizontalFrame_8, 0, 1, 1, 1)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.location)
        self.horizontalFrame_4.setStyleSheet("QFrame {\n"
                                             "    border: 1px solid black;\n"
                                             "}")
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_up = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_up.setMinimumSize(QtCore.QSize(0, 0))
        self.label_up.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_up.setStyleSheet("QLabel {\n"
                                    "    border: none;\n"
                                    "    border-right: 1px solid black;\n"
                                    "}")
        self.label_up.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_up.setObjectName("label_up")
        self.horizontalLayout_3.addWidget(self.label_up)
        self.input_up = QtWidgets.QLineEdit(self.horizontalFrame_4)
        self.input_up.setStyleSheet("QLineEdit {\n"
                                    "    border: none;\n"
                                    "}\n"
                                    "")
        self.input_up.setObjectName("input_up")
        self.horizontalLayout_3.addWidget(self.input_up)
        self.gridLayout_3.addWidget(self.horizontalFrame_4, 2, 0, 1, 1)
        self.horizontalFrame_9 = QtWidgets.QFrame(self.location)
        self.horizontalFrame_9.setStyleSheet("QFrame {\n"
                                             "    border: 1px solid black;\n"
                                             "}")
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_down = QtWidgets.QLabel(self.horizontalFrame_9)
        self.label_down.setMinimumSize(QtCore.QSize(0, 0))
        self.label_down.setStyleSheet("QLabel {\n"
                                      "    border: none;\n"
                                      "    border-right: 1px solid black;\n"
                                      "}")
        self.label_down.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_down.setObjectName("label_down")
        self.horizontalLayout_9.addWidget(self.label_down)
        self.input_down = QtWidgets.QLineEdit(self.horizontalFrame_9)
        self.input_down.setStyleSheet("QLineEdit {\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "")
        self.input_down.setObjectName("input_down")
        self.horizontalLayout_9.addWidget(self.input_down)
        self.gridLayout_3.addWidget(self.horizontalFrame_9, 2, 1, 1, 1)
        self.container_dock2 = QtWidgets.QFrame(self.tab_home)
        self.container_dock2.setGeometry(QtCore.QRect(100, 500, 131, 121))
        self.container_dock2.setStyleSheet("QFrame {\n"
                                           "    background-color: rgba(74, 255, 155, 80);\n"
                                           "}")
        self.container_dock2.setObjectName("container_dock2")
        self.gridLayout = QtWidgets.QGridLayout(self.container_dock2)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.button_dock_7 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_7.setStyleSheet("")
        self.button_dock_7.setObjectName("button_dock_7")
        self.gridLayout.addWidget(self.button_dock_7, 0, 0, 1, 1)
        self.button_dock_5 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_5.setObjectName("button_dock_5")
        self.gridLayout.addWidget(self.button_dock_5, 1, 1, 1, 1)
        self.button_dock_1 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_1.setObjectName("button_dock_1")
        self.gridLayout.addWidget(self.button_dock_1, 2, 0, 1, 1)
        self.button_dock_3 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_3.setObjectName("button_dock_3")
        self.gridLayout.addWidget(self.button_dock_3, 2, 2, 1, 1)
        self.button_dock_2 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_2.setObjectName("button_dock_2")
        self.gridLayout.addWidget(self.button_dock_2, 2, 1, 1, 1)
        self.button_dock_6 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_6.setObjectName("button_dock_6")
        self.gridLayout.addWidget(self.button_dock_6, 1, 2, 1, 1)
        self.button_dock_9 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_9.setObjectName("button_dock_9")
        self.gridLayout.addWidget(self.button_dock_9, 0, 2, 1, 1)
        self.button_dock_8 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_8.setObjectName("button_dock_8")
        self.gridLayout.addWidget(self.button_dock_8, 0, 1, 1, 1)
        self.button_dock_4 = QtWidgets.QPushButton(self.container_dock2)
        self.button_dock_4.setObjectName("button_dock_4")
        self.gridLayout.addWidget(self.button_dock_4, 1, 0, 1, 1)
        self.label_window_size_title = QtWidgets.QLabel(self.tab_home)
        self.label_window_size_title.setGeometry(QtCore.QRect(480, 480, 72, 21))
        self.label_window_size_title.setMinimumSize(QtCore.QSize(0, 18))
        self.label_window_size_title.setStyleSheet("QLabel {\n"
                                                   "    background-color: rgba(70, 70, 255, 50)\n"
                                                   "}")
        self.label_window_size_title.setObjectName("label_window_size_title")
        self.verticalFrame_2 = QtWidgets.QFrame(self.tab_home)
        self.verticalFrame_2.setGeometry(QtCore.QRect(480, 500, 361, 91))
        self.verticalFrame_2.setStyleSheet("QFrame {\n"
                                           "    background-color: rgba(70, 70, 255, 50)\n"
                                           "}")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalFrame_5 = QtWidgets.QFrame(self.verticalFrame_2)
        self.horizontalFrame_5.setStyleSheet("QFrame {\n"
                                             "    border: 1px solid black;\n"
                                             "    /* background-color: none; */\n"
                                             "}")
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_width = QtWidgets.QLabel(self.horizontalFrame_5)
        self.label_width.setMinimumSize(QtCore.QSize(0, 0))
        self.label_width.setStyleSheet("QLabel {\n"
                                       "    border: none;\n"
                                       "    border-right: 1px solid black;\n"
                                       "    background-color: none;\n"
                                       "}")
        self.label_width.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_width.setObjectName("label_width")
        self.horizontalLayout_5.addWidget(self.label_width)
        self.input_width = QtWidgets.QLineEdit(self.horizontalFrame_5)
        self.input_width.setStyleSheet("QLineEdit {\n"
                                       "    border: none;\n"
                                       "}\n"
                                       "")
        self.input_width.setObjectName("input_width")
        self.horizontalLayout_5.addWidget(self.input_width)
        self.label_height = QtWidgets.QLabel(self.horizontalFrame_5)
        self.label_height.setMinimumSize(QtCore.QSize(0, 0))
        self.label_height.setStyleSheet("QLabel {\n"
                                        "    border: none;\n"
                                        "    border-left: 1px solid black;\n"
                                        "    border-right: 1px solid black;\n"
                                        "    background-color: none;\n"
                                        "}")
        self.label_height.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_height.setObjectName("label_height")
        self.horizontalLayout_5.addWidget(self.label_height)
        self.input_height = QtWidgets.QLineEdit(self.horizontalFrame_5)
        self.input_height.setStyleSheet("QLineEdit {\n"
                                        "    border: none;\n"
                                        "    margin-right: 10px;\n"
                                        "}\n"
                                        "")
        self.input_height.setObjectName("input_height")
        self.horizontalLayout_5.addWidget(self.input_height)
        self.width_height_center = QtWidgets.QCheckBox(self.horizontalFrame_5)
        self.width_height_center.setEnabled(True)
        self.width_height_center.setTristate(False)
        self.width_height_center.setObjectName("width_height_center")
        self.horizontalLayout_5.addWidget(self.width_height_center)
        self.verticalLayout_3.addWidget(self.horizontalFrame_5)
        self.horizontalFrame_10 = QtWidgets.QFrame(self.verticalFrame_2)
        self.horizontalFrame_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalFrame_10.setStyleSheet("QFrame {\n"
                                              "    border: 1px solid black;\n"
                                              "    /* background-color: none; */\n"
                                              "}")
        self.horizontalFrame_10.setObjectName("horizontalFrame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalFrame_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.input_big_small_px = QtWidgets.QLineEdit(self.horizontalFrame_10)
        self.input_big_small_px.setStyleSheet("QLineEdit {\n"
                                              "    border: none;\n"
                                              "}\n"
                                              "")
        self.input_big_small_px.setObjectName("input_big_small_px")
        self.horizontalLayout_10.addWidget(self.input_big_small_px)
        self.button_big = QtWidgets.QPushButton(self.horizontalFrame_10)
        self.button_big.setMinimumSize(QtCore.QSize(100, 0))
        self.button_big.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_big.setStyleSheet("QPushButton {\n"
                                      "    border-left: 1px solid black;\n"
                                      "    /*\n"
                                      "    margin-left: 7px;\n"
                                      "    margin-right: 7px;\n"
                                      "    */\n"
                                      "    height: 100%;\n"
                                      "}")
        self.button_big.setObjectName("button_big")
        self.horizontalLayout_10.addWidget(self.button_big)
        self.button_small = QtWidgets.QPushButton(self.horizontalFrame_10)
        self.button_small.setMinimumSize(QtCore.QSize(100, 0))
        self.button_small.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_small.setStyleSheet("QPushButton {\n"
                                        "    margin-right: 7px;\n"
                                        "    height: 100%;\n"
                                        "}")
        self.button_small.setObjectName("button_small")
        self.horizontalLayout_10.addWidget(self.button_small)
        self.max_min_center = QtWidgets.QCheckBox(self.horizontalFrame_10)
        self.max_min_center.setObjectName("max_min_center")
        self.horizontalLayout_10.addWidget(self.max_min_center)
        self.verticalLayout_3.addWidget(self.horizontalFrame_10)
        self.label_default_size = QtWidgets.QLabel(self.tab_home)
        self.label_default_size.setGeometry(QtCore.QRect(240, 600, 101, 21))
        self.label_default_size.setStyleSheet("QLabel {\n"
                                              "    background-color: rgba(35, 171, 255, 60);\n"
                                              "}")
        self.label_default_size.setObjectName("label_default_size")
        self.size = QtWidgets.QFrame(self.tab_home)
        self.size.setGeometry(QtCore.QRect(240, 620, 601, 171))
        self.size.setStyleSheet("QFrame {\n"
                                "    /* padding: 5px; */\n"
                                "    background-color: rgba(35, 171, 255, 60);\n"
                                "    margin: 0;\n"
                                "    padding: 0;\n"
                                "}\n"
                                "\n"
                                "")
        self.size.setObjectName("size")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.size)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalFrame_13 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_13.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_13.setObjectName("horizontalFrame_13")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalFrame_13)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.horizontalFrame_13)
        self.label_6.setMinimumSize(QtCore.QSize(25, 25))
        self.label_6.setMaximumSize(QtCore.QSize(25, 25))
        self.label_6.setStyleSheet("QLabel {\n"
                                   "    background-color: none;\n"
                                   "}")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/ico/终端.ico"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        self.button_size_cmd = QtWidgets.QPushButton(self.horizontalFrame_13)
        self.button_size_cmd.setObjectName("button_size_cmd")
        self.horizontalLayout_16.addWidget(self.button_size_cmd)
        self.gridLayout_4.addWidget(self.horizontalFrame_13, 2, 2, 1, 1)
        self.horizontalFrame_11 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_11.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalFrame_11.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_11.setObjectName("horizontalFrame_11")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalFrame_11)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame_11)
        self.label_4.setMinimumSize(QtCore.QSize(25, 25))
        self.label_4.setMaximumSize(QtCore.QSize(25, 25))
        self.label_4.setStyleSheet("QLabel {\n"
                                   "    \n"
                                   "}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/png/explorer.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.button_size_explorer = QtWidgets.QPushButton(self.horizontalFrame_11)
        self.button_size_explorer.setObjectName("button_size_explorer")
        self.horizontalLayout_14.addWidget(self.button_size_explorer)
        self.gridLayout_4.addWidget(self.horizontalFrame_11, 2, 1, 1, 1)
        self.horizontalFrame_19 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_19.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_19.setObjectName("horizontalFrame_19")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalFrame_19)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_14 = QtWidgets.QLabel(self.horizontalFrame_19)
        self.label_14.setMinimumSize(QtCore.QSize(25, 25))
        self.label_14.setMaximumSize(QtCore.QSize(25, 25))
        self.label_14.setStyleSheet("QLabel {\n"
                                    "    background-color: none;\n"
                                    "}")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/png/查找.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_22.addWidget(self.label_14)
        self.button_size_find = QtWidgets.QPushButton(self.horizontalFrame_19)
        self.button_size_find.setObjectName("button_size_find")
        self.horizontalLayout_22.addWidget(self.button_size_find)
        self.gridLayout_4.addWidget(self.horizontalFrame_19, 3, 1, 1, 1)
        self.horizontalFrame_18 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_18.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_18.setObjectName("horizontalFrame_18")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalFrame_18)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.horizontalFrame_18)
        self.label_13.setMinimumSize(QtCore.QSize(25, 25))
        self.label_13.setMaximumSize(QtCore.QSize(25, 25))
        self.label_13.setStyleSheet("QLabel {\n"
                                    "    background-color: none;\n"
                                    "}")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/png/屏幕.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_21.addWidget(self.label_13)
        self.button_size_screen = QtWidgets.QPushButton(self.horizontalFrame_18)
        self.button_size_screen.setObjectName("button_size_screen")
        self.horizontalLayout_21.addWidget(self.button_size_screen)
        self.gridLayout_4.addWidget(self.horizontalFrame_18, 0, 1, 1, 1)
        self.horizontalFrame_16 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_16.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_16.setObjectName("horizontalFrame_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalFrame_16)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_9 = QtWidgets.QLabel(self.horizontalFrame_16)
        self.label_9.setMinimumSize(QtCore.QSize(25, 25))
        self.label_9.setMaximumSize(QtCore.QSize(25, 25))
        self.label_9.setStyleSheet("QLabel {\n"
                                   "\n"
                                   "}")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/ico/idea.ico"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_19.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.horizontalFrame_16)
        self.label_10.setMinimumSize(QtCore.QSize(25, 25))
        self.label_10.setMaximumSize(QtCore.QSize(25, 25))
        self.label_10.setStyleSheet("QLabel {\n"
                                    "\n"
                                    "}")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/ico/pycharm.ico"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_19.addWidget(self.label_10)
        self.button_size_jetbrains = QtWidgets.QPushButton(self.horizontalFrame_16)
        self.button_size_jetbrains.setObjectName("button_size_jetbrains")
        self.horizontalLayout_19.addWidget(self.button_size_jetbrains)
        self.gridLayout_4.addWidget(self.horizontalFrame_16, 0, 2, 1, 1)
        self.horizontalFrame_3 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.horizontalFrame_3.setStyleSheet("QFrame {\n"
                                             "    margin: 0;\n"
                                             "    padding: 0;\n"
                                             "    background-color: none;\n"
                                             "}")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.horizontalFrame_3)
        self.label.setMinimumSize(QtCore.QSize(25, 25))
        self.label.setMaximumSize(QtCore.QSize(25, 25))
        self.label.setStyleSheet("QLabel {\n"
                                 "\n"
                                 "}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ico/wechat.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.button_size_wechat = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.button_size_wechat.setObjectName("button_size_wechat")
        self.horizontalLayout_11.addWidget(self.button_size_wechat)
        self.gridLayout_4.addWidget(self.horizontalFrame_3, 3, 0, 1, 1)
        self.horizontalFrame_17 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_17.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalFrame_17.setMaximumSize(QtCore.QSize(16777215, 25))
        self.horizontalFrame_17.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_17.setObjectName("horizontalFrame_17")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalFrame_17)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_12 = QtWidgets.QLabel(self.horizontalFrame_17)
        self.label_12.setMinimumSize(QtCore.QSize(25, 25))
        self.label_12.setMaximumSize(QtCore.QSize(25, 25))
        self.label_12.setStyleSheet("QLabel {\n"
                                    "    background-color: none;\n"
                                    "}")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/png/全屏.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_20.addWidget(self.label_12)
        self.button_size_max = QtWidgets.QPushButton(self.horizontalFrame_17)
        self.button_size_max.setObjectName("button_size_max")
        self.horizontalLayout_20.addWidget(self.button_size_max)
        self.gridLayout_4.addWidget(self.horizontalFrame_17, 0, 0, 1, 1)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalFrame_6.setStyleSheet("QFrame {\n"
                                             "    margin: 0;\n"
                                             "    padding: 0;\n"
                                             "    background-color: none;\n"
                                             "}")
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_2.setMinimumSize(QtCore.QSize(25, 25))
        self.label_2.setMaximumSize(QtCore.QSize(25, 25))
        self.label_2.setStyleSheet("QLabel {\n"
                                   "\n"
                                   "}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/ico/cloudmusic2.ico"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.button_size_cloudmusic = QtWidgets.QPushButton(self.horizontalFrame_6)
        self.button_size_cloudmusic.setObjectName("button_size_cloudmusic")
        self.horizontalLayout_13.addWidget(self.button_size_cloudmusic)
        self.gridLayout_4.addWidget(self.horizontalFrame_6, 2, 0, 1, 1)
        self.horizontalFrame_12 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_12.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_12.setObjectName("horizontalFrame_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalFrame_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame_12)
        self.label_5.setMinimumSize(QtCore.QSize(25, 25))
        self.label_5.setMaximumSize(QtCore.QSize(25, 25))
        self.label_5.setStyleSheet("QLabel {\n"
                                   "\n"
                                   "}")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/ico/钉钉.ico"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_15.addWidget(self.label_5)
        self.label_11 = QtWidgets.QLabel(self.horizontalFrame_12)
        self.label_11.setMinimumSize(QtCore.QSize(25, 25))
        self.label_11.setMaximumSize(QtCore.QSize(25, 25))
        self.label_11.setStyleSheet("QLabel {\n"
                                    "\n"
                                    "}")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/ico/夸克.ico"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.button_size_dingding = QtWidgets.QPushButton(self.horizontalFrame_12)
        self.button_size_dingding.setObjectName("button_size_dingding")
        self.horizontalLayout_15.addWidget(self.button_size_dingding)
        self.gridLayout_4.addWidget(self.horizontalFrame_12, 1, 2, 1, 1)
        self.horizontalFrame_15 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_15.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_15.setObjectName("horizontalFrame_15")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalFrame_15)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_8 = QtWidgets.QLabel(self.horizontalFrame_15)
        self.label_8.setMinimumSize(QtCore.QSize(25, 25))
        self.label_8.setMaximumSize(QtCore.QSize(25, 25))
        self.label_8.setStyleSheet("QLabel {\n"
                                   "\n"
                                   "}")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/png/默认.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_18.addWidget(self.label_8)
        self.button_size_default = QtWidgets.QPushButton(self.horizontalFrame_15)
        self.button_size_default.setObjectName("button_size_default")
        self.horizontalLayout_18.addWidget(self.button_size_default)
        self.gridLayout_4.addWidget(self.horizontalFrame_15, 1, 1, 1, 1)
        self.default_size_center = QtWidgets.QCheckBox(self.size)
        self.default_size_center.setEnabled(True)
        self.default_size_center.setMaximumSize(QtCore.QSize(16777215, 25))
        self.default_size_center.setStyleSheet("QCheckBox {\n"
                                               "    /* background-color: rgba(35, 171, 255, 60); */\n"
                                               "    margin: 0;\n"
                                               "    padding: 0;\n"
                                               "    height: 100%;\n"
                                               "}\n"
                                               "\n"
                                               "")
        self.default_size_center.setTristate(False)
        self.default_size_center.setObjectName("default_size_center")
        self.gridLayout_4.addWidget(self.default_size_center, 3, 2, 1, 1)
        self.horizontalFrame_14 = QtWidgets.QFrame(self.size)
        self.horizontalFrame_14.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalFrame_14.setMaximumSize(QtCore.QSize(16777215, 25))
        self.horizontalFrame_14.setStyleSheet("QFrame {\n"
                                              "    margin: 0;\n"
                                              "    padding: 0;\n"
                                              "    background-color: none;\n"
                                              "}")
        self.horizontalFrame_14.setObjectName("horizontalFrame_14")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalFrame_14)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame_14)
        self.label_7.setMinimumSize(QtCore.QSize(25, 25))
        self.label_7.setMaximumSize(QtCore.QSize(25, 25))
        self.label_7.setStyleSheet("QLabel {\n"
                                   "\n"
                                   "}")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/ico/chatglm.ico"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_17.addWidget(self.label_7)
        self.button_size_chatglm = QtWidgets.QPushButton(self.horizontalFrame_14)
        self.button_size_chatglm.setObjectName("button_size_chatglm")
        self.horizontalLayout_17.addWidget(self.button_size_chatglm)
        self.gridLayout_4.addWidget(self.horizontalFrame_14, 1, 0, 1, 1)
        self.label_window_status = QtWidgets.QLabel(self.tab_home)
        self.label_window_status.setGeometry(QtCore.QRect(10, 630, 72, 21))
        self.label_window_status.setStyleSheet("QLabel {\n"
                                               "    background-color: rgba(255, 85, 0, 70)\n"
                                               "}")
        self.label_window_status.setObjectName("label_window_status")
        self.gridFrame = QtWidgets.QFrame(self.tab_home)
        self.gridFrame.setGeometry(QtCore.QRect(10, 650, 221, 141))
        self.gridFrame.setStyleSheet("QFrame {\n"
                                     "    background-color: rgba(255, 85, 0, 70)\n"
                                     "}")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.button_window_hide = QtWidgets.QPushButton(self.gridFrame)
        self.button_window_hide.setStyleSheet("QPushButton {\n"
                                              "    color: rgb(129, 129, 129)\n"
                                              "}")
        self.button_window_hide.setObjectName("button_window_hide")
        self.gridLayout_6.addWidget(self.button_window_hide, 4, 0, 1, 1)
        self.button_window_show = QtWidgets.QPushButton(self.gridFrame)
        self.button_window_show.setStyleSheet("")
        self.button_window_show.setObjectName("button_window_show")
        self.gridLayout_6.addWidget(self.button_window_show, 0, 0, 1, 1)
        self.button_window_max = QtWidgets.QPushButton(self.gridFrame)
        self.button_window_max.setObjectName("button_window_max")
        self.gridLayout_6.addWidget(self.button_window_max, 1, 0, 1, 1)
        self.button_window_close = QtWidgets.QPushButton(self.gridFrame)
        self.button_window_close.setStyleSheet("QPushButton {\n"
                                               "    color: rgb(255, 0, 4)\n"
                                               "}")
        self.button_window_close.setObjectName("button_window_close")
        self.gridLayout_6.addWidget(self.button_window_close, 0, 1, 1, 1)
        self.button_window_min = QtWidgets.QPushButton(self.gridFrame)
        self.button_window_min.setObjectName("button_window_min")
        self.gridLayout_6.addWidget(self.button_window_min, 1, 1, 1, 1)
        self.label_table_title = QtWidgets.QLabel(self.tab_home)
        self.label_table_title.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_table_title.setObjectName("label_table_title")
        self.table_info_data = QtWidgets.QTableWidget(self.tab_home)
        self.table_info_data.setGeometry(QtCore.QRect(10, 30, 831, 281))
        self.table_info_data.setStyleSheet("QTableWidget {\n"
                                           "    width: 100%;\n"
                                           "}")
        self.table_info_data.setObjectName("table_info_data")
        self.table_info_data.setColumnCount(2)
        self.table_info_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_info_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info_data.setHorizontalHeaderItem(1, item)
        self.table_info_data.horizontalHeader().setVisible(False)
        self.table_info_data.horizontalHeader().setCascadingSectionResizes(False)
        self.table_info_data.horizontalHeader().setDefaultSectionSize(420)
        self.pin_to_top = QtWidgets.QCheckBox(self.tab_home)
        self.pin_to_top.setGeometry(QtCore.QRect(710, 10, 121, 19))
        self.pin_to_top.setObjectName("pin_to_top")
        window_root.addTab(self.tab_home, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.opacity = QtWidgets.QFrame(self.tab)
        self.opacity.setGeometry(QtCore.QRect(10, 30, 241, 151))
        self.opacity.setStyleSheet("QFrame {\n"
                                   "    background-color: rgba(170, 0, 255, 80);\n"
                                   "}")
        self.opacity.setObjectName("opacity")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.opacity)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_opacity_80 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_80.setObjectName("button_opacity_80")
        self.gridLayout_5.addWidget(self.button_opacity_80, 0, 2, 1, 1)
        self.button_opacity_100 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_100.setObjectName("button_opacity_100")
        self.gridLayout_5.addWidget(self.button_opacity_100, 0, 0, 1, 1)
        self.button_opacity_90 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_90.setObjectName("button_opacity_90")
        self.gridLayout_5.addWidget(self.button_opacity_90, 0, 1, 1, 1)
        self.button_opacity_70 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_70.setObjectName("button_opacity_70")
        self.gridLayout_5.addWidget(self.button_opacity_70, 1, 0, 1, 1)
        self.button_opacity_40 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_40.setObjectName("button_opacity_40")
        self.gridLayout_5.addWidget(self.button_opacity_40, 2, 0, 1, 1)
        self.button_opacity_30 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_30.setObjectName("button_opacity_30")
        self.gridLayout_5.addWidget(self.button_opacity_30, 2, 1, 1, 1)
        self.button_opacity_60 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_60.setObjectName("button_opacity_60")
        self.gridLayout_5.addWidget(self.button_opacity_60, 1, 1, 1, 1)
        self.button_opacity_50 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_50.setObjectName("button_opacity_50")
        self.gridLayout_5.addWidget(self.button_opacity_50, 1, 2, 1, 1)
        self.button_opacity_20 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_20.setObjectName("button_opacity_20")
        self.gridLayout_5.addWidget(self.button_opacity_20, 2, 2, 1, 1)
        self.button_opacity_10 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_10.setObjectName("button_opacity_10")
        self.gridLayout_5.addWidget(self.button_opacity_10, 3, 0, 1, 1)
        self.button_opacity_0 = QtWidgets.QPushButton(self.opacity)
        self.button_opacity_0.setObjectName("button_opacity_0")
        self.gridLayout_5.addWidget(self.button_opacity_0, 3, 1, 1, 1)
        self.label_opacity = QtWidgets.QLabel(self.tab)
        self.label_opacity.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_opacity.setStyleSheet("QLabel {\n"
                                         "    background-color: rgba(170, 0, 255, 80);\n"
                                         "}")
        self.label_opacity.setObjectName("label_opacity")
        window_root.addTab(self.tab, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        window_root.addTab(self.tab_config, "")

        self.retranslateUi(window_root)
        window_root.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window_root)

    def retranslateUi(self, window_root):
        _translate = QtCore.QCoreApplication.translate
        window_root.setWindowTitle(_translate("window_root", "TabWidget"))
        self.label_select_title.setText(_translate("window_root", "选中窗口详情："))
        self.label_window_title.setText(_translate("window_root", "标题窗口："))
        self.label_size.setText(_translate("window_root", "窗口大小："))
        self.label_xy.setText(_translate("window_root", " 窗口位置："))
        self.label_pid.setText(_translate("window_root", " 进程号："))
        self.label_tid.setText(_translate("window_root", " 线程号："))
        self.label_process_path.setText(_translate("window_root", "启动程序："))
        self.label_status.setText(_translate("window_root", "窗口状态："))
        self.label_status2.setText(_translate("window_root", " 判断状态："))
        self.label_opacity_2.setText(_translate("window_root", " 透明度："))
        self.label_window_dock.setText(_translate("window_root", "窗口停靠："))
        self.button_dock_left.setText(_translate("window_root", "←"))
        self.button_dock_down.setText(_translate("window_root", "↓"))
        self.button_dock_up.setText(_translate("window_root", "↑"))
        self.button_dock_right.setText(_translate("window_root", "→"))
        self.button_dock_h_center.setText(_translate("window_root", "↔"))
        self.button_dock_v_center.setText(_translate("window_root", "↕"))
        self.label_window_xy_title.setText(_translate("window_root", "窗口位置："))
        self.label_left.setText(_translate("window_root", " L "))
        self.label_right.setText(_translate("window_root", " R "))
        self.label_up.setText(_translate("window_root", " U "))
        self.label_down.setText(_translate("window_root", " D "))
        self.button_dock_7.setText(_translate("window_root", "↖"))
        self.button_dock_5.setText(_translate("window_root", "□"))
        self.button_dock_1.setText(_translate("window_root", "↙"))
        self.button_dock_3.setText(_translate("window_root", "↘"))
        self.button_dock_2.setText(_translate("window_root", "↓"))
        self.button_dock_6.setText(_translate("window_root", "→"))
        self.button_dock_9.setText(_translate("window_root", "↗"))
        self.button_dock_8.setText(_translate("window_root", "↑"))
        self.button_dock_4.setText(_translate("window_root", "←"))
        self.label_window_size_title.setText(_translate("window_root", "窗口大小："))
        self.label_width.setText(_translate("window_root", " W "))
        self.label_height.setText(_translate("window_root", " H "))
        self.width_height_center.setText(_translate("window_root", "是否居中"))
        self.button_big.setText(_translate("window_root", "MAX"))
        self.button_small.setText(_translate("window_root", "min"))
        self.max_min_center.setText(_translate("window_root", "是否居中"))
        self.label_default_size.setText(_translate("window_root", "预设窗口大小："))
        self.button_size_cmd.setText(_translate("window_root", "1259x770"))
        self.button_size_explorer.setText(_translate("window_root", "1313x750"))
        self.button_size_find.setText(_translate("window_root", "960x600"))
        self.button_size_screen.setText(_translate("window_root", "1920x1080"))
        self.button_size_jetbrains.setText(_translate("window_root", "1750x1030"))
        self.button_size_wechat.setText(_translate("window_root", "1080x800"))
        self.button_size_max.setText(_translate("window_root", "1938x1098"))
        self.button_size_cloudmusic.setText(_translate("window_root", "1321x940"))
        self.button_size_dingding.setText(_translate("window_root", "1410x809"))
        self.button_size_default.setText(_translate("window_root", "1550x980"))
        self.default_size_center.setText(_translate("window_root", "是否居中"))
        self.button_size_chatglm.setText(_translate("window_root", "1663x938"))
        self.label_window_status.setText(_translate("window_root", "窗口状态："))
        self.button_window_hide.setText(_translate("window_root", "隐藏"))
        self.button_window_show.setText(_translate("window_root", "显示"))
        self.button_window_max.setText(_translate("window_root", "最大化"))
        self.button_window_close.setText(_translate("window_root", "关闭"))
        self.button_window_min.setText(_translate("window_root", "最小化"))
        self.label_table_title.setText(_translate("window_root", "所有窗口进程总览："))
        item = self.table_info_data.horizontalHeaderItem(0)
        item.setText(_translate("window_root", "标题"))
        item = self.table_info_data.horizontalHeaderItem(1)
        item.setText(_translate("window_root", "启动程序"))
        self.pin_to_top.setText(_translate("window_root", "置顶当前窗口"))
        window_root.setTabText(window_root.indexOf(self.tab_home), _translate("window_root", "主页"))
        self.button_opacity_80.setText(_translate("window_root", "80%"))
        self.button_opacity_100.setText(_translate("window_root", "100%"))
        self.button_opacity_90.setText(_translate("window_root", "90%"))
        self.button_opacity_70.setText(_translate("window_root", "70%"))
        self.button_opacity_40.setText(_translate("window_root", "40%"))
        self.button_opacity_30.setText(_translate("window_root", "30%"))
        self.button_opacity_60.setText(_translate("window_root", "60%"))
        self.button_opacity_50.setText(_translate("window_root", "50%"))
        self.button_opacity_20.setText(_translate("window_root", "20%"))
        self.button_opacity_10.setText(_translate("window_root", "10%"))
        self.button_opacity_0.setText(_translate("window_root", "0%"))
        self.label_opacity.setText(_translate("window_root", "窗口透明度："))
        window_root.setTabText(window_root.indexOf(self.tab), _translate("window_root", "窗口透明度(扩展)"))
        window_root.setTabText(window_root.indexOf(self.tab_config), _translate("window_root", "配置文件(扩展)"))



import lw0_0_3.interface.ico_rc
